import { spawn } from "node:child_process";
import { existsSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import type { PackageManager } from "./package-manager";

/**
 * Lockfile filename a successful `<pm> install` writes.
 *
 * `bun: "bun.lock"` is intentional — bun 1.2 made the
 * text-based `bun.lock` (TOML-ish) the default lockfile, and
 * the legacy binary `bun.lockb` is no longer generated by `bun
 * install` on fresh projects. The CI matrix pins `bun@1.3.13`
 * (see `.github/workflows/ci.yaml`'s `setup-bun` step), and
 * the `engines.node >=22.22.0` floor in the published packages
 * effectively requires a bun new enough to honour the text-
 * lockfile default. The auto-review periodically re-flags this
 * as if `bun.lockb` were still the default — that hasn't been
 * true since bun 1.2 (Jan 2025).
 */
const LOCKFILE_BY_PM: Record<PackageManager, string> = {
  npm: "package-lock.json",
  pnpm: "pnpm-lock.yaml",
  yarn: "yarn.lock",
  bun: "bun.lock",
};

/**
 * Snapshot of the closest-enclosing `<pm>` lockfile at a moment
 * in time. The pre-install snapshot is what the round-39 git-
 * init gate compares against to decide whether a non-zero
 * install exit still produced a usable tree.
 */
export interface LockfileSnapshot {
  /** True when a lockfile of the expected name was on disk. */
  exists: boolean;
  /** `mtime` in ms; `0` when the file didn't exist or was unreadable. */
  mtimeMs: number;
}

/**
 * Find the closest-enclosing `<pm>` lockfile (cwd-or-above) and
 * record its existence + mtime. Walks ancestors because scaffold
 * targets inside an existing workspace (`monorepo/packages/foo`)
 * install against a root-hoisted lockfile, not a cwd-local one.
 * Mirrors `hasEnclosingYarnLock`'s walk policy and applies the
 * same termination signal (`dirname() === self`).
 *
 * Returns `{ exists: false, mtimeMs: 0 }` when `pm` is
 * `undefined`, no lockfile exists anywhere up the tree, or the
 * file is unreadable (rare permissions edge — falls through to
 * "no snapshot" so the comparison can't assert a stale mtime).
 */
export function snapshotLockfile(
  cwd: string,
  pm: PackageManager | undefined,
): LockfileSnapshot {
  if (pm === undefined) return { exists: false, mtimeMs: 0 };
  const lockfile = LOCKFILE_BY_PM[pm];
  let dir = cwd;
  while (true) {
    const candidate = join(dir, lockfile);
    if (existsSync(candidate)) {
      try {
        return { exists: true, mtimeMs: statSync(candidate).mtimeMs };
      } catch {
        return { exists: false, mtimeMs: 0 };
      }
    }
    const parent = dirname(dir);
    if (parent === dir) return { exists: false, mtimeMs: 0 };
    dir = parent;
  }
}

/**
 * True when the closest-enclosing lockfile state at `cwd` is
 * materially different from `before` — either freshly created or
 * with a forward-moving `mtime`. Used by the CLI's git-init gate
 * to recover from a non-zero install exit that still produced a
 * complete tree (pnpm 11 and bun on Windows have been observed
 * exiting non-zero AFTER writing both `node_modules` and the
 * lockfile — round-39 Copilot review).
 *
 * Comparing against a *pre-install* snapshot is what closes the
 * round-39-follow-up Codex P1 hazard: a workspace-subdir scaffold
 * has a pre-existing root lockfile, so any `existsSync`-only
 * check would treat a totally failed install as "lockfile
 * landed" and proceed with `git init` over an untouched tree.
 * Forward-moving mtime is the proof we need; equal mtime + same
 * existence means "install didn't change anything" and the
 * caller should NOT recover.
 */
export function lockfileChangedSince(
  cwd: string,
  pm: PackageManager | undefined,
  before: LockfileSnapshot,
): boolean {
  const after = snapshotLockfile(cwd, pm);
  if (!before.exists && after.exists) return true;
  if (after.mtimeMs > before.mtimeMs) return true;
  return false;
}

/**
 * Snapshot of the `node_modules` state relevant to `cwd` at a
 * moment in time. Captures `cwd/node_modules` AND every
 * ancestor `node_modules` above `cwd`, keyed by absolute path.
 * The recovery gate's diff compares BEFORE/AFTER and treats
 * EITHER a freshly-appeared `node_modules` along the chain OR
 * forward-moving mtime on any pre-existing one as "install
 * touched the dependency tree".
 *
 * History — the right shape took several rounds to settle:
 *
 *   - Round 39 follow-up #1 (initial): `hasEnclosingNodeModules`
 *     ancestor existence check. Too lax: a failed install in a
 *     monorepo subdir saw a stale parent `node_modules` and
 *     passed the gate.
 *   - Round 39 follow-up #2: cwd-only snapshot/diff. Too
 *     narrow: workspace-subdir scaffolds with hoisted installs
 *     have ZERO `cwd/node_modules` activity even on success.
 *   - Round 39 follow-up #3: cwd + closest-enclosing-by-path
 *     recorded at snapshot time. Better, but still missed three
 *     cases Codex P2 (round 40) flagged:
 *       (a) `before.enclosing` was null but install creates a
 *           new ancestor `node_modules` (workspace hoist).
 *       (b) `before.enclosing` pinned a far ancestor, but
 *           install creates a CLOSER ancestor (the captured
 *           far path stays unchanged).
 *       (c) the probe relies on the directory's own mtime,
 *           which can stay flat if the package manager only
 *           writes inside subdirectories (e.g. pnpm under
 *           `node_modules/.pnpm/*`). For first-time scaffold
 *           installs this is rare in practice — top-level
 *           symlinks ARE added so the parent's mtime advances
 *           — but the constraint is documented here so future
 *           changes don't mistake it for a load-bearing
 *           guarantee. Lockfile-changed pairs with this check
 *           to backstop (c) on partial-reinstall edges.
 *   - Round 40 (current): track ALL `node_modules` paths along
 *     the chain in a Map; re-walk after install; ANY new path
 *     OR mtime-advance returns true. (a)(b) closed; (c)
 *     accepted as the probe's known limitation.
 */
export interface NodeModulesSnapshot {
  /** State of `cwd/node_modules` at snapshot time. */
  cwd: { exists: boolean; mtimeMs: number };
  /**
   * Every `node_modules` directory above `cwd` (strict
   * ancestors), keyed by absolute path → mtime captured at
   * snapshot time. `cwd/node_modules` is intentionally NOT
   * recorded here; it has its own slot. Empty Map when no
   * ancestor `node_modules` exists.
   */
  enclosing: ReadonlyMap<string, number>;
}

function statMtimeOrZero(path: string): { exists: boolean; mtimeMs: number } {
  if (!existsSync(path)) return { exists: false, mtimeMs: 0 };
  try {
    return { exists: true, mtimeMs: statSync(path).mtimeMs };
  } catch {
    return { exists: false, mtimeMs: 0 };
  }
}

/**
 * Walk strictly ABOVE `cwd` and return every existing
 * `node_modules` path in the chain along with its mtime.
 * `cwd/node_modules` itself is excluded — that slot is
 * tracked separately by `snapshotNodeModules`.
 */
function collectEnclosingNodeModules(cwd: string): Map<string, number> {
  const acc = new Map<string, number>();
  let dir = dirname(cwd);
  while (true) {
    const candidate = join(dir, "node_modules");
    const snap = statMtimeOrZero(candidate);
    if (snap.exists) acc.set(candidate, snap.mtimeMs);
    const parent = dirname(dir);
    if (parent === dir) break; // reached filesystem root
    dir = parent;
  }
  return acc;
}

export function snapshotNodeModules(cwd: string): NodeModulesSnapshot {
  return {
    cwd: statMtimeOrZero(join(cwd, "node_modules")),
    enclosing: collectEnclosingNodeModules(cwd),
  };
}

/**
 * True when the `node_modules` state relevant to `cwd` has
 * materially advanced since `before`. Paired with
 * `lockfileChangedSince` in the CLI's git-init recovery gate:
 * BOTH must hold for a non-zero `<pm> install` exit to be
 * treated as "install effectively succeeded".
 *
 * Returns true when ANY of:
 *   - `cwd/node_modules` was freshly created or its mtime
 *     advanced (standalone or package-local install path).
 *   - A previously-existing ancestor `node_modules` (recorded
 *     by absolute path at snapshot time) has a forward-moving
 *     mtime (hoisted install into a pre-existing workspace
 *     `node_modules`).
 *   - A `node_modules` newly appeared at any level above `cwd`
 *     (hoisted install that materializes the workspace's
 *     `node_modules` for the first time, e.g. yarn-berry
 *     `node-modules` linker on a fresh checkout, or pnpm
 *     `--shamefully-hoist` against a previously empty parent).
 *
 * Returns false when:
 *   - Nothing along the chain changed (failed install over a
 *     pre-existing tree → gate rejects → CLI surfaces retry
 *     guidance instead of running git init on an untouched
 *     project).
 *
 * Known limitation (documented for future-you, accepted as
 * out of scope of this gate): the probe stats each
 * `node_modules` directory's own mtime. Package managers that
 * write only inside subdirectories (e.g. partial pnpm
 * reinstall touching `node_modules/.pnpm/<pkg>/*`) without
 * adding/removing top-level entries can leave the parent
 * mtime untouched. For the FIRST-TIME scaffold install this
 * predicate is meant to gate, top-level symlinks/folders ARE
 * added by every package manager, so the mtime advances. The
 * paired `lockfileChangedSince` check (an AND in the recovery
 * gate) catches the partial-reinstall edge that this probe
 * alone might miss.
 */
export function nodeModulesChangedSince(
  cwd: string,
  before: NodeModulesSnapshot,
): boolean {
  const cwdAfter = statMtimeOrZero(join(cwd, "node_modules"));
  if (!before.cwd.exists && cwdAfter.exists) return true;
  if (cwdAfter.mtimeMs > before.cwd.mtimeMs) return true;

  // Re-walk ancestors AFTER install: any path not in `before`
  // (newly appeared) OR a known path with forward-moving mtime
  // signals install activity. Re-walking — rather than only
  // re-stat'ing the BEFORE-captured paths — closes both the
  // null-before case and the closer-ancestor-created-during-
  // install case.
  const enclosingAfter = collectEnclosingNodeModules(cwd);
  for (const [path, afterMtime] of enclosingAfter) {
    const beforeMtime = before.enclosing.get(path);
    if (beforeMtime === undefined) return true;
    if (afterMtime > beforeMtime) return true;
  }
  return false;
}

/**
 * Walk from `cwd` up to filesystem root looking for the first
 * `yarn.lock`. Mirrors yarn's own resolution: in a yarn-berry
 * workspace, `yarn install` from a subdirectory writes to the
 * ENCLOSING workspace's lockfile, so the immutable-install check
 * has to look at the ancestor tree, not just `cwd`.
 *
 * Walks until `dirname()` returns the same path it was given —
 * the canonical "reached filesystem root" signal. The earlier
 * 20-iteration cap (round 27 defensive symlink guard) was
 * misclassifying real deeply-nested workspace paths as having
 * no enclosing lockfile, then setting
 * `YARN_ENABLE_IMMUTABLE_INSTALLS=false` and bypassing yarn-
 * berry's CI immutability guard — exactly the rewrite hazard
 * the round-27 walk was supposed to prevent (PR #99 round 39
 * Codex P2). `dirname` is purely syntactic (doesn't follow
 * symlinks) so it terminates at the root naturally.
 *
 * (PR #99 round 27 — Copilot flagged the cwd-only check as
 * unsafe in the workspace-subdir case: a user scaffolding into
 * `monorepo/packages/foo` would otherwise have the override
 * fire, letting yarn rewrite the root `monorepo/yarn.lock`
 * silently in CI.)
 */
function hasEnclosingYarnLock(cwd: string): boolean {
  let dir = cwd;
  while (true) {
    if (existsSync(join(dir, "yarn.lock"))) return true;
    const parent = dirname(dir);
    if (parent === dir) return false; // reached filesystem root
    dir = parent;
  }
}

/**
 * Run `install` through the given package manager in `cwd` with stdio
 * inherited. Patterned after create-next-app's helper: `ADBLOCK` /
 * `DISABLE_OPENCOLLECTIVE` suppress promotional output, and
 * `NODE_ENV=development` keeps pnpm from skipping devDependencies
 * (pnpm treats `production` as "no dev deps").
 */
export async function install(
  packageManager: PackageManager,
  cwd: string,
): Promise<void> {
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    ADBLOCK: "1",
    NODE_ENV: "development",
    DISABLE_OPENCOLLECTIVE: "1",
  };
  // yarn 4 (berry) flips `enableImmutableInstalls` to `true` by
  // default whenever it sees `CI=1`. The very first install of a
  // freshly scaffolded project has no `yarn.lock`, so an immutable
  // install refuses to write one and exits with `YN0028: The
  // lockfile would have been created by this install, which is
  // explicitly forbidden`. Real users running `arkor init
  // --use-yarn` / `create-arkor --use-yarn` in their CI hit this.
  //
  // Override only when there's no enclosing `yarn.lock` in the
  // ancestor tree — i.e. the fresh-scaffold case. With a lockfile
  // already present (in cwd OR in any ancestor — yarn-berry
  // workspace subdirs share the root's lockfile), we MUST NOT
  // bypass yarn's immutability check: doing so would silently let
  // install rewrite the committed lockfile, which the safety
  // check exists to prevent in CI.
  //
  // History:
  //   - Round 13: introduced the unconditional override.
  //   - Round 17: narrowed to fresh scaffolds via cwd-only
  //     `existsSync(yarn.lock)` after Copilot flagged the
  //     lockfile-rewrite hazard.
  //   - Round 27: extended the check to walk up the ancestor
  //     tree after Copilot pointed out workspace-subdir scaffolds
  //     bypassed the round-17 guard (cwd has no lockfile, but the
  //     enclosing workspace does).
  //
  // yarn 1 / npm / pnpm / bun all ignore the variable, so the
  // gate is a no-op outside yarn-berry.
  //
  // Round 32 (Copilot, PR #99): when there IS an enclosing
  // `yarn.lock` we MUST clear any inherited
  // `YARN_ENABLE_IMMUTABLE_INSTALLS=false` from the parent
  // shell. Without the explicit delete, a CI that exports the
  // var globally (or a developer who set it for some other
  // workflow) would leak it through `{ ...process.env, ... }`
  // and bypass the very immutability check the lockfile-present
  // branch is supposed to preserve. Keep the override only on
  // the fresh-scaffold branch where bypassing is intentional.
  //
  // Round 39 (Codex P2, PR #99): on Windows env-var lookup is
  // case-insensitive (`PATH` == `Path` == `path`), and Node
  // passes through whatever casing the parent shell used. A
  // `yarn_enable_immutable_installs=false` (or any other
  // casing) inherited from the parent would otherwise survive
  // a case-exact `delete env.YARN_ENABLE_IMMUTABLE_INSTALLS`
  // and yarn-berry on Windows would still honour it. Strip
  // every case-insensitive match before deciding whether to
  // re-set the canonical form. POSIX env vars are case-
  // sensitive so the loop is a no-op outside Windows in
  // practice, but the pattern is portable.
  if (packageManager === "yarn") {
    for (const key of Object.keys(env)) {
      if (key.toUpperCase() === "YARN_ENABLE_IMMUTABLE_INSTALLS") {
        delete env[key];
      }
    }
    if (!hasEnclosingYarnLock(cwd)) {
      env.YARN_ENABLE_IMMUTABLE_INSTALLS = "false";
    }
    // else: keep it deleted — yarn-berry's default `CI=1` behaviour
    // is to refuse a lockfile-rewriting install, exactly the safety
    // we want with an enclosing lockfile.
  }
  return new Promise((resolve, reject) => {
    const child = spawn(packageManager, ["install"], {
      cwd,
      stdio: "inherit",
      // `pnpm` / `yarn` / `bun` are `.cmd` shims on Windows — spawn needs a
      // shell to resolve them.
      shell: process.platform === "win32",
      env,
    });
    child.on("error", reject);
    child.on("close", (code) => {
      if (code !== 0) {
        reject(
          new Error(`\`${packageManager} install\` exited with code ${code}`),
        );
        return;
      }
      resolve();
    });
  });
}
