#!/usr/bin/env node
import { resolve } from "node:path";
import process from "node:process";
import * as clack from "@clack/prompts";
import { Command } from "commander";
import {
  gitInitialCommit,
  install,
  isInGitRepo,
  resolvePackageManager,
  sanitise,
  scaffold,
  templateChoices,
  type PackageManager,
  type TemplateId,
} from "@arkor/cli-internal";

interface RunOptions {
  dir?: string;
  name?: string;
  template?: TemplateId;
  yes?: boolean;
  skipInstall?: boolean;
  /** Undefined when neither `--use-*` nor UA detection yielded a pm. */
  packageManager: PackageManager | undefined;
  /** `true` when the user explicitly passed `--git`. Undefined → prompt. */
  git?: boolean;
  /** `true` when the user explicitly passed `--skip-git` (no prompt, no init). */
  skipGit?: boolean;
}

const MANUAL_INSTALL_HINT =
  "install dependencies (npm i / pnpm install / yarn / bun install)";

function isInteractive(): boolean {
  return Boolean(process.stdout.isTTY) && !process.env.CI;
}

/**
 * Decide whether to run `git init` + initial commit, then (optionally) do it.
 *
 * Policy:
 *   - `--git`       → run without asking
 *   - `--skip-git`  → skip without asking
 *   - `-y` / `--yes` (without --skip-git) → run without asking (matches the
 *     general "accept defaults" semantics; the prompt's default is yes)
 *   - interactive   → prompt (default = yes)
 *   - non-interactive & no flag → skip (never auto-init silently)
 *   - already inside a git repo → skip unconditionally
 */
async function maybeGitInit(
  cwd: string,
  options: RunOptions,
): Promise<void> {
  if (options.skipGit) return;

  if (await isInGitRepo(cwd)) {
    clack.log.info("Directory is already inside a git repository — skipping git init.");
    return;
  }

  let shouldInit: boolean;
  if (options.git === true || options.yes) {
    shouldInit = true;
  } else if (isInteractive()) {
    const answer = await clack.confirm({
      message: "Initialise a git repository and create an initial commit?",
      initialValue: true,
    });
    if (clack.isCancel(answer)) {
      clack.cancel("Cancelled.");
      process.exit(1);
    }
    shouldInit = answer;
  } else {
    shouldInit = false;
  }

  if (!shouldInit) return;

  clack.log.step("Initialising git repository");
  try {
    const result = await gitInitialCommit(
      cwd,
      "Initial commit from Create Arkor",
    );
    if (result.signingFallback) {
      clack.log.warn(
        "Commit signing failed — created an unsigned commit. Re-sign with `git commit --amend -S` once your signing setup is fixed.",
      );
    }
  } catch (err) {
    clack.log.warn(err instanceof Error ? err.message : String(err));
    clack.log.info("You can initialise git manually later.");
  }
}

async function run(options: RunOptions): Promise<void> {
  clack.intro("create-arkor");

  const cwd = options.dir ? resolve(options.dir) : process.cwd();
  const defaultName = sanitise(
    options.name ??
      (options.dir
        ? options.dir.split(/[/\\]/).pop()!
        : process.cwd().split(/[/\\]/).pop()!),
  );

  // Always sanitise — `defaultName` is already sanitised, but `options.name`
  // straight from `--name` is not, and falls through to package.json as-is
  // when `--yes` skips the interactive prompt.
  let name = sanitise(options.name ?? defaultName);
  let template: TemplateId = options.template ?? "minimal";

  if (!options.yes && isInteractive()) {
    const chosenName = await clack.text({
      message: "Project name?",
      initialValue: defaultName,
      validate: (v) => (v.trim() ? undefined : "Project name cannot be empty"),
    });
    if (clack.isCancel(chosenName)) {
      clack.cancel("Cancelled.");
      process.exit(1);
    }
    name = sanitise(chosenName);

    const chosenTemplate = await clack.select<TemplateId>({
      message: "Starter template?",
      initialValue: template,
      options: templateChoices(),
    });
    if (clack.isCancel(chosenTemplate)) {
      clack.cancel("Cancelled.");
      process.exit(1);
    }
    template = chosenTemplate;
  }

  const spin = clack.spinner();
  spin.start(`Scaffolding in ${cwd}`);
  const { files } = await scaffold({ cwd, name, template });
  spin.stop("Done");

  clack.note(
    files.map((f) => `${f.action.padEnd(8)} ${f.path}`).join("\n"),
    "Files",
  );

  const pm = options.packageManager;

  let installed = false;
  if (!options.skipInstall && pm) {
    clack.log.step(`Installing dependencies with ${pm}`);
    try {
      await install(pm, cwd);
      installed = true;
    } catch (err) {
      clack.log.warn(err instanceof Error ? err.message : String(err));
      clack.log.info(
        `Retry manually: cd ${options.dir ?? "."} && ${pm} install`,
      );
    }
  }

  // git init runs *after* install so the lockfile generated by the package
  // manager lands in the initial commit; otherwise the tree would be dirty
  // immediately after `--git` / `-y` and the bootstrap commit wouldn't be
  // reproducible.
  await maybeGitInit(cwd, options);

  const installLine = installed
    ? null
    : pm
      ? `  ${pm} install`
      : `  ${MANUAL_INSTALL_HINT}`;
  const trainLine =
    pm && pm !== "npm" ? `  ${pm} arkor train` : `  npx arkor train`;

  clack.outro(
    [
      `Next steps:`,
      `  cd ${options.dir ?? "."}`,
      ...(installLine ? [installLine] : []),
      trainLine,
    ].join("\n"),
  );
}

const program = new Command();

program
  .name("create-arkor")
  .description("Scaffold a TypeScript arkor training project.")
  .argument("[dir]", "target directory (default: current directory)")
  .option("--name <name>", "project name (default: directory name)")
  .option(
    "--template <template>",
    "starter template: minimal | alpaca | chatml",
  )
  .option("-y, --yes", "skip interactive prompts and accept the defaults")
  .option("--skip-install", "skip installing dependencies after scaffolding")
  .option("--use-npm", "force npm as the package manager")
  .option("--use-pnpm", "force pnpm as the package manager")
  .option("--use-yarn", "force yarn as the package manager")
  .option("--use-bun", "force bun as the package manager")
  .option(
    "--git",
    "initialise a git repo and create an initial commit (skips the prompt)",
  )
  .option("--skip-git", "skip the git init prompt and do not initialise git")
  .action(
    async (
      dir: string | undefined,
      opts: {
        name?: string;
        template?: string;
        yes?: boolean;
        skipInstall?: boolean;
        useNpm?: boolean;
        usePnpm?: boolean;
        useYarn?: boolean;
        useBun?: boolean;
        git?: boolean;
        skipGit?: boolean;
      },
    ) => {
      if (opts.git && opts.skipGit) {
        throw new Error("Pick one of --git / --skip-git, not both.");
      }
      const template =
        opts.template === "minimal" ||
        opts.template === "alpaca" ||
        opts.template === "chatml"
          ? opts.template
          : undefined;
      const packageManager = resolvePackageManager({
        useNpm: opts.useNpm,
        usePnpm: opts.usePnpm,
        useYarn: opts.useYarn,
        useBun: opts.useBun,
      });
      await run({
        dir,
        name: opts.name,
        template,
        yes: opts.yes,
        skipInstall: opts.skipInstall,
        packageManager,
        git: opts.git,
        skipGit: opts.skipGit,
      });
    },
  );

program.parseAsync(process.argv).catch((err) => {
  process.stderr.write(
    `create-arkor failed: ${err instanceof Error ? err.message : String(err)}\n`,
  );
  process.exit(1);
});
